version: '3'
services:

  phpfpm:
    image: 10up/phpfpm
    container_name: meetup_phpfpm
    build: images/phpfpm
    volumes:
      - ./www:/var/www/html
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - ~/.ssh:/root/.ssh
    restart: always
    extra_hosts:
      - "${HOST}.localhost:172.18.0.1"

  nginx:
    container_name: meetup_nginx
    depends_on:
      - phpfpm
    ports:
      - "${NGINX_PORT}:80"
    image: nginx:latest
    volumes:
      - ./www:/var/www/html
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always
